### ISSUE TITLE
Helptags missing

### ISSUE THREAD

**Issue by z0rc** [tmux-plugins/vim-tmux#11]
I'm using pathogen to manage vim plugins. It automatically generates missing helptags, see http://usevim.com/2012/12/21/vim-101-help-tags/. The tags are placed at `doc/tags` of this plugin root folder.

Please either create and commit this file or add it to gitignore.

**Comment by z0rc** [comment]
I missed #10 when filed this one. Closing. Please merge the outstanding PR.

**Comment by bruno-** [comment]
It's merged!
