### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nfischer** [tmux-plugins/vim-tmux#16]
Is this project licensed under a particular open source license? I couldn't find a license file in the repo.

Awesome plugin, by the way!

**Comment by bruno-** [comment]
Hi,
I added a note about license [here](https://github.com/tmux-plugins/vim-tmux#license). So, the plugin was forked and I'm not sure what the license was before. All the additions made after forking are MIT.

Since I didn't create the plugin from scratch I'm not sure if I can declare it 100% MIT..

**Comment by nfischer** [comment]
Thanks!
