### ISSUE TITLE
Numbers in option names highlighted wrong

### ISSUE THREAD

**Issue by y** [tmux-plugins/vim-tmux#19]
From #18 
> Please reopen the issue if I got something wrong..

Users aren't allowed to re-open issues if they don't have permissions on the github repo, so I'm creating a new issue in case you don't notice the comment on the closed issue. See https://github.com/tmux-plugins/vim-tmux/issues/18#issuecomment-313891076 for more details confirming original issue and a patch.

**Comment by bruno-** [comment]
Hi, thanks for the notification. I reopened the original issue and will close this one.
