### ISSUE TITLE
E185: Cannot find color scheme 'OceanicNext'

### ISSUE THREAD

**Issue by olalonde** [tmux-plugins/vim-tmux#24]
```vim
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'voronianski/oceanic-next-color-scheme'
call plug#end()

if (has("termguicolors"))
 set termguicolors
endif

" Theme
syntax enable
colorscheme OceanicNext
let g:airline_theme='OceanicnNxt'
```

When I run this, I'm getting: `E185: Cannot find color scheme 'OceanicNext'`

**Comment by bruno-** [comment]
Hey,

did you open this issue by accident on this repo `vim-tmux`? I think that might be the case, so I'll close the issue. Please reopen if you think this really is related.

**Comment by olalonde** [comment]
Oopss, yep sorry!
