### ISSUE TITLE
Error on sourcing `.tmux.conf` with `:make`

### ISSUE THREAD

**Issue by rkiyanchuk** [tmux-plugins/vim-tmux#5]
When I try to source the `.tmux.conf` file using `:make`, I get the following error:

```
.tmux.conf: No such file or directory

Press ENTER or type command to continue
```

I was able to fix this only by specifying explicit location of the file in the `vim-tmux/compiler/tmux.vim` plugin like this:

```
CompilerSet makeprg=tmux\ source-file\ ~/.tmux.conf
```

Do you know if this is a bug, or am I missing something?

Tmux version is `1.9`.

Thanks!

**Comment by bruno-** [comment]
Hey, thanks for reporting.
Yea, this should work, so there's a bug somewhere. I just quickly tried this and couldn't reproduce the issue.

What happens if you change the line in `compiler/tmux.vim` to this?

```
CompilerSet makeprg=tmux\ source-file\ %:p
```

Note: only `:p` has been appended to the line.

**Comment by rkiyanchuk** [comment]
@bruno-, thanks for the quick reply!

Yes, `CompilerSet makeprg=tmux\ source-file\ %:p` worked without problems.

**Comment by bruno-** [comment]
Great, I've updated the compiler so now `%:p` is always used.

**Comment by rkiyanchuk** [comment]
@bruno- Cool, also thanks for the plugins and all your work on making `tmux` better!
